# Generated by Django 4.1.7 on 2023-03-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.JSONField(max_length=50),
        ),
    ]
